<?php
$str_check = FALSE;
include_once("sb_ii_check.php");

if ($str_check) {
    $field[] = array('cve_perfil', 'perfil_modulo', '0', 0);

    $field[] = array('cve_modulo', 'perfil_modulo', '1', "");
    $field[] = array('key_modulo', 'perfil_modulo', '1', "");
    $allf = array();
    $allv = array();
    foreach ($field as $afield) {
        $allf[] = $afield[0];
        $allv[] = $afield[3];
    }
    $IdPrin = '';
    $tabla = 'sb_perfil_modulo,sb_modulo';
    $strWhere = "Where sb_perfil_modulo.cve_perfil=" . $__SESSION->getValueSession('cveperfil');
    $strWhere.=" and sb_perfil_modulo.cve_modulo=" . $__SESSION->getValueSession('mod');
    $strWhere.=" and sb_perfil_modulo.cve_modulo=sb_modulo.cve_modulo";
    $strWhere.=" and sb_modulo.sta_modulo<>0";
    $classval = new Entidad($allf, $allv);
    $classval->Consultar($allf, $IdPrin, $tabla, $strWhere);
    $str_valmodulo = "MOD_NOVALIDO";
    if ($classval->NumReg > 0) {
        $str_valmodulo = "MOD_VALIDO";
        $a_key = explode(',', $classval->key_modulo);
        $a_search = array();
        $a_search[0] = array('des_modulo', 'grp_modulo');
        $a_search[1] = array('Descripcion', 'Grupo');
        $a_search[2] = array('text', 'num');
        $field = array();
        $allf = array();
        $allv = array();
        $hab_bus_only = true;
        /* $field[]=array('0 - nombre','1 - etiqueta','2 - tipo de impresion(0: no imprimible, 1: imprimible, 2:dato de hiden principal)',
          '3 - tipo de objeto','4 - modificable(0: no mofificable, 1:modificable, 2: mofificable solo para nuevo registro)',
          '5 - valores alternos','6 - tipo de dato','7 - Valor inicial','8 - width de columna en brow', '9 - width de columna en view'
          '10 - longitud maxima en caja de texto', '11 - cadena de validaci&oacute;n', 12 - requiered); */
        $entidad = 'MODULOS';
        $id_prin = 'cve_modulo';
        $strWhere = "Where ";
        $a_order = array('cve_modulo');
        switch ($__SESSION->getValueSession('cveperfil')) {
            case 1:
                $tablas_c = 'sb_modulo';
                $a_order[] = 'grp_modulo';
                $a_order[] = 'pos_modulo';
                break;
//		case $_SESSION['cveperfil']<>1:
//			$strWhere.=" cve_usuario=".$_SESSION['cveusuario'];
//			$tablas_c='usuario';
//			$a_order[]=$id_prin;
//			break;
        }
        /*         * ****inicia condicion de busqueda */
        if ($__SESSION->getValueSession('valSearch') <> "") {
            foreach ($a_search[0] as $cont_search => $itemTmpSearch) {
                if ($__SESSION->getValueSession('itemSearch') == $itemTmpSearch) {
                    if ($strWhere <> "Where ")
                        $strWhere.=" and ";
                    if ($a_search[2][$cont_search] == 'num') {
                        $strWhere.=$__SESSION->getValueSession('itemSearch') . " = " . ($__SESSION->getValueSession('valSearch') * 1);
                    } else {
                        $strWhere.='upper(' . $__SESSION->getValueSession('itemSearch') . ") like upper('%" . trim($__SESSION->getValueSession('valSearch')) . "%')";
                    }
                    break;
                }
            }
        }
        /*         * ****termina condicion de busqueda */
// configuraciones para fechas de busqueda aqui
        $srchperiodo = 1;
        $srchperiodo_field = "res.fecha_captura";
//configuracion fechas busqueda
        $conf_date_b[0][0] = "campo_b1";
        $conf_date_b[0][1] = "
            changeMonth: true,
            changeYear: true,
            controlType: 'select',
            oneLine: true,
            dateFormat: 'dd/mm/yy',
            timeFormat: '',
            buttonText: '<i class=\'fa icon-calendar\'></i>',
            dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
            monthNamesShort: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            showOn: 'button',
            showClose: true,
            closeText:'Cerrar',            
            timeText:'',
            " . //agregar accione javascript aqui
//"            beforeShow: valid_fecha,".
//"            onSelect: accion_select,"
                "";
        //agregar funcion es si los hay
//         $conf_date_b[0][2]="function valid_fecha() {
//            }";   


        $conf_date_b[1][0] = "campo_b2";
        $conf_date_b[1][1] = "
            changeMonth: true,
            changeYear: true,
            controlType: 'select',
            oneLine: true,
            dateFormat: 'dd/mm/yy',
            timeFormat: '',
            buttonText: '<i class=\'fa icon-calendar\'></i>',
            dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
            monthNamesShort: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            showOn: 'button',
            showOn: 'button',
            showClose: true,
            closeText:'Cerrar',            
            timeText:'',            
            ";
//         $conf_date[1][2]="function valid_fecha() {
//            }";            
//fin configuracion fechas busqueda   

        echo '<div id="ven_actv" style="display:none" class="ventana_ac" title="Iconos"></div>';
        $arreglo_icon = forma_ii();
//        echo '<pre>';
//        print_r($arreglo_icon[1]);die();
        if ($strWhere == "Where ")
            $strWhere = "";
        //$strWhere.=" prioridad.estado <> FALSE";
        //$items0='perfil.*';
        $tabla = 'sb_modulo';
        $strDistintic = "SELECT count(*) as count_r FROM sb_modulo " . $strWhere;
        $intlimit = 15;
        $a_separs = array();
        $a_separs[] = array(1, 'Datos Generales', 8, 'separ_verde');
        $a_separs[] = array(2, 'Otros datos', 8, 'separ_verde');

        $field[] = array('cve_modulo', 'Clave', '1', 'label', '0', '', 'int', 0, 80, 20, 0, '', 0, 1, array(1, 1, 6));
        $field[] = array('des_modulo', 'Descripcion de Modulo', '1', 'text', '1', '', 'char', "", 200, 100, 100, '', 1, array(1, 'col-12 col-md-12', 'col-12 col-md-6'), array(1, 1, 6));
        $field[] = array('sta_modulo', 'Status', '1', 'check', '1', '', 'char', "", 70, 10, 0, '', 0, array(1, 'col-12 col-md-12', 'col-12 col-md-6'), array(1, 1, 3), '', 1);

        $field[] = array('url_modulo', 'URL de Modulo', '1', 'text', '1', '', 'char', "", 140, 50, 60, '', 1, array(1, 'col-12 col-md-12', 'col-12 col-md-6'), array(1, 1, 3));

        $field[] = array('grp_modulo', 'Grupo de Modulo', '1', 'text', '1', '', 'int', "0", 150, 20, 4, '', 1, array(1, 'col-12 col-md-12', 'col-12 col-md-6'), array(1, 1, 2));
        $field[] = array('pos_modulo', 'Posici&oacute;n de Modulo', '1', 'text', '1', '', 'int', "0", 170, 20, 4, '', 1, array(1, 'col-12 col-md-12', 'col-12 col-md-6'), array(1, 1, 2));
        $field[] = array('niv_modulo', 'Nivel de Modulo', '1', 'text', '1', '', 'int', "0", 150, 20, 2, '', 1, array(1, 'col-12 col-md-12', 'col-12 col-md-6'), array(1, 1, 2));

        $field[] = array('url_include', 'URL de Include de Modulo', '1', 'text', '1', '', 'char', "", 210, 60, 60, '', 1, array(1, 'col-12 col-md-12', 'col-12 col-md-6'), array(1, 1, 6));
        $field[] = array('parametro', 'Cadena de parametros de Modulo', '1', 'text', '1', '', 'char', "", 300, 80, 250, '', 0, array(1, 'col-12 col-md-12', 'col-12 col-md-6'), array(1, 1, 6));

        $field[] = array('hiddhab', 'Habilitar para manejo de periodo de captura', '1', 'check', '1', '', 'char', "", 100, 20, 10, '', 0, array(1, 'col-12 col-md-12', 'col-12 col-md-6'), array(1, 1, 6), '', 1, 'hab. cap.');
        $field[] = array('display', 'Desplegar menu', '1', 'check', '1', '', 'char', "", 300, 20, 10, '', 0, array(1, 'col-12 col-md-12', 'col-12 col-md-6'), array(1, 1, 6), '', 1, 'Habilitar para organigrama');

        $field[] = array('des_modulo_padre', array('Modulo depende',null,'acce'), '1', 'text', '1', "", 'char', "", 150, 70, 50, '', 0, array(1, 'col-12 col-md-12', 'col-12 col-md-6'), array(1, 1, 6), '', 0, 'Modulo depende', 0, '', '', '', '', '',
            " onKeyUp=\"initializeObjText(event,'cve_modulo_padre','0');auto_disp('get_elementmodulo','des_modulo_padre',20,100,400,event,':lenMin_00_sendObj_des_modulo_padre','getObj_des_modulo_padre','getObj_cve_modulo_padre','focusObj_des_modulo_padre','aTitles_document.titlesMod');\" autocomplete = \"off\"",
            '', '', '', 'getKeyFalse(event); ');

        if ($__SESSION->getValueSession('opc') == 2 || $__SESSION->getValueSession('opc') == 3 || isset($_POST['btnActualiza']) || isset($_POST['btnGuarda'])) {
            $field[] = array('cve_modulo_padre', 'cve_modulo_padre', '1', 'hidden', '1', '', 'int', '0', 120, 50, 11, '', 0, 1, array(1, 1, 3));
            $field[] = array('icono', "Icono <a onmousedown='javascript:mostrar_iconos()' onmouseup='javascript:mostrar_iconos()' title='Mostrar Actividades'><i id='i_princam' class='fa fa-search'></i></a>", '1', 'label', '1', '', 'char', "", 200, 60, 100, '', 0, array(1, 'col-12 col-md-12', 'col-12 col-md-6'), array(1, 1, 4));
            $field[] = array('color_icono', 'Color del Icono', '1', 'text', '1', '', 'char', "", 50, 20, 20, '', 0, array(1, 'col-12 col-md-12', 'col-12 col-md-6'), array(1, 1, 1));
        } else
            $field[] = array('icono', 'Icono', '1', 'select', '1', array($arreglo_icon[0], $arreglo_icon[1]), 'char', '', 70, 10, 2, '', 0, array(1, 'col-12 col-md-12', 'col-12 col-md-6'), array(1, 1, 5), '', 0, 'Icono');
         if ($__SESSION->getValueSession('opc') == 2 || $__SESSION->getValueSession('opc') == 3){
             $field[]=array('iconom',"",'1','label','1','','char',"",200,60,100,'',0,0,array(1,1,1));	        
         }
        // para fromulario modal clave a mandar
        $keyFieldsPop = array('cve_modulo');

        $conf_date = "
            changeMonth: true,
            changeYear: true,
            controlType: 'select',
            oneLine: true,
            dateFormat: 'dd/mm/yy',
            timeFormat: 'HH:mm',
            buttonText: '<i class=\'fa icon-calendar\'></i>',
            dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
            monthNamesShort: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],            
            " .
//"            beforeShow: valid_fecha,".
//"            onSelect: accion_select,"
                "";
//         $conf_funciones="function valid_fecha() {
//            }";
//         $conf_funciones="";
//        $field[] = array('fecha_captura', 'fecha captura', '1', 'text', '1', '', 'date', date("d/m/Y H:m"), 100, 10, 10, '', 1, array(1,'col-12 col-md-12','col-12 col-md-6'), array(1, 1, 1), '', 0, 'fecha captura', 0, '',
//                '', '', '', '', 'onKeyUp="modifyChars(this,\'-\',\'/\');"',/*conf date jquery*/$conf_date,/* funcion*/$conf_funciones);    
//	$per_val=array();
//	$per_des=array();
//	$classconsul = new Entidad(array('cve_perfil','des_perfil'),array(0,''));
//	$classconsul->ListaEntidades(array('cve_perfil'),'sb_perfil','');
//	for ($i=0; $i<$classconsul->NumReg; $i++) {
//		$classconsul->VerDatosEntidad($i,array('cve_perfil','des_perfil'));
//		$per_val[]=$classconsul->cve_perfil;
//		$per_des[]=$classconsul->des_perfil;
//	}
//	        
//        $field[]=array('cve_perfil','Perfil','1','select','1',array($per_val,$per_des),'int',0,700,20,2,'',1,array(1,'col-12 col-md-12','col-12 col-md-6'),array(1,1,6));



        $a_print = array();
                $a_print[] = array("./rep/reporientacionpdf.php?fparam=il_orientacion&", " ", array('cve_modulo'), '20');	         
        $setdel = '';
        $keyFields = array('cve_modulo');
        $keyTypeFields = array('num'); //int,text
        $array_noprint_ent = array('null');
        $suma_width = 0;
        $rwitem = 'null';
        $strwentidad = "entidad35.php";
        $ent_add = "addentidad0002.php";
        $ent_upd = "updentidad0002.php";
        $boolNoEditable = FALSE;
//	$boolNoUpdate=FALSE;
//	$boolNoDelete=FALSE;
        $strSelf = "sb_modulo.php";
        $__SESSION->setValueSession('niveles', array('sb_modulo.php', 'sb_perfil_modulo.php'));
        $intNivel = 1;
        $intNW = 40;
        $str_idniv1 = "fa fa-user-plus";
        $str_titleniv1 = "Acceso de perfil";
        $str_estilo1 = "color:green;";

        $suma_width = 0;
        $numcols = 0;
        foreach ($field as $afield) {
            if ($afield[2] == '1') {
                $suma_width+=$afield[8];
                $numcols+=1;
            }
        }
        $awidths = array('300', '250', '650');
        //	$str_ent=$PHP_SELF."?ent=i_indicador&id=";
        //	if (isset($_GET['opccal']) && $_GET['opccal']==1)
        //		$str_ent=$PHP_SELF."?opccal=".$_GET['opccal']."&ent=i_proyecto&id=";
        //	}
    }
} else {
    include_once("../config/cfg.php");
    include_once("../lib/lib_function.php");
    include_once("sb_ii_refresh.php");
}

function fnBeforeButtons($objectTmp) {
    global $boolResetButtons;
    global $intNivel;
    global $lblNivel2;
    global $lblNivel3;
    //global $lblNivel4;
    global $intNivelTmp;
    global $lblNivel2Tmp;
    global $lblNivel3Tmp;
    //global $lblNivel4Tmp;
    global $suma_width_aux;
    global $suma_width_aux2;
    global $suma_width_auxTmp;

    global $a_pop_e3;
    global $a_popTitle_e3;
    global $a_popObVal_e3;
    global $a_popContent_e3;
    global $a_popPos_e3;

    $boolResetButtons = false;
    if (in_array(($objectTmp->sta_modulo) + 0, array(1))) {
        $a_pop_e3 = array('des_modulo'); //campo donde pinta icon =>para llamar modal
        $a_popTitle_e3 = array('Desactivar modulo'); //titulo del modal
        $a_popObVal_e3 = array('des_modulo'); //return
        $a_popContent_e3 = array('lst_datos2'); //archivo php en raiz
        $a_popPos_e3 = array(1); //pos del arreglo para llamar il en archivo lst_datos2.php
    }
}

function fnBeforeLoad() { // oculta el campo de sexo al inicio de la plantilla
    echo '<script language="JavaScript">'
    . '$("#color_icono").addClass( "jscolor" );'
    . '</script>';
}

//function fnImplementInDel(){
//	if (isset($_POST['cve_modulo'])){
//				$classent = new Entidad(array('cve_modulo'),array(0));
//				$strConDel=" cve_modulo=".$_POST['cve_modulo'];
//				$classent->Eliminar('perfil_modulo','','cve_modulo',1,$strConDel);
//				$classent->Eliminar('modulo_habilitado','','cve_modulo',1,$strConDel);
//	}
//}
function forma_ii() {
    $arreglo_iconos = array(
        'fa-heart',
        'fa-star',
        'fa-star-o',
        'fa-user',
        'fa-film',
        'fa-th-large',
        'fa-th',
        'fa-th-list',
        'fa-check',
        'fa-remove',
        'fa-close',
        'fa-times',
        'fa-search-plus',
        'fa-search-minus',
        'fa-power-off',
        'fa-signal',
        'fa-gear',
        'fa-cog',
        'fa-trash-o',
        'fa-home',
        'fa-file-o',
        'fa-clock-o',
        'fa-road',
        'fa-download',
        'fa-arrow-circle-o-down',
        'fa-arrow-circle-o-up',
        'fa-inbox',
        'fa-play-circle-o',
        'fa-rotate-right',
        'fa-repeat',
        'fa-refresh',
        'fa-list-alt',
        'fa-lock',
        'fa-flag',
        'fa-headphones',
        'fa-volume-off',
        'fa-volume-down',
        'fa-volume-up',
        'fa-qrcode',
        'fa-barcode',
        'fa-tag',
        'fa-tags',
        'fa-book',
        'fa-bookmark',
        'fa-print',
        'fa-camera',
        'fa-font',
        'fa-bold',
        'fa-italic',
        'fa-text-height',
        'fa-text-width',
        'fa-align-left',
        'fa-align-center',
        'fa-align-right',
        'fa-align-justify',
        'fa-list',
        'fa-dedent',
        'fa-outdent',
        'fa-indent',
        'fa-video-camera',
        'fa-photo',
        'fa-image',
        'fa-picture-o',
        'fa-pencil',
        'fa-map-marker',
        'fa-adjust',
        'fa-tint',
        'fa-edit',
        'fa-pencil-square-o',
        'fa-share-square-o',
        'fa-check-square-o',
        'fa-arrows',
        'fa-step-backward',
        'fa-fast-backward',
        'fa-backward',
        'fa-play',
        'fa-pause',
        'fa-stop',
        'fa-forward',
        'fa-fast-forward',
        'fa-step-forward',
        'fa-eject',
        'fa-chevron-left',
        'fa-chevron-right',
        'fa-plus-circle',
        'fa-minus-circle',
        'fa-times-circle',
        'fa-check-circle',
        'fa-question-circle',
        'fa-info-circle',
        'fa-crosshairs',
        'fa-times-circle-o',
        'fa-check-circle-o',
        'fa-ban',
        'fa-arrow-left',
        'fa-arrow-right',
        'fa-arrow-up',
        'fa-arrow-down',
        'fa-mail-forward',
        'fa-share',
        'fa-expand',
        'fa-compress',
        'fa-plus',
        'fa-minus',
        'fa-asterisk',
        'fa-exclamation-circle',
        'fa-gift',
        'fa-leaf',
        'fa-fire',
        'fa-eye',
        'fa-eye-slash',
        'fa-warning',
        'fa-exclamation-triangle',
        'fa-plane',
        'fa-calendar',
        'fa-random',
        'fa-comment',
        'fa-magnet',
        'fa-chevron-up',
        'fa-chevron-down',
        'fa-retweet',
        'fa-shopping-cart',
        'fa-folder',
        'fa-folder-open',
        'fa-arrows-v',
        'fa-arrows-h',
        'fa-bar-chart-o',
        'fa-bar-chart',
        'fa-twitter-square',
        'fa-facebook-square',
        'fa-camera-retro',
        'fa-key',
        'fa-gears',
        'fa-cogs',
        'fa-comments',
        'fa-thumbs-o-up',
        'fa-thumbs-o-down',
        'fa-star-half',
        'fa-heart-o',
        'fa-sign-out',
        'fa-linkedin-square',
        'fa-thumb-tack',
        'fa-external-link',
        'fa-sign-in',
        'fa-trophy',
        'fa-github-square',
        'fa-upload',
        'fa-lemon-o',
        'fa-phone',
        'fa-square-o',
        'fa-bookmark-o',
        'fa-phone-square',
        'fa-twitter',
        'fa-facebook-f',
        'fa-facebook',
        'fa-github',
        'fa-unlock',
        'fa-credit-card',
        'fa-feed',
        'fa-rss',
        'fa-hdd-o',
        'fa-bullhorn',
        'fa-bell',
        'fa-certificate',
        'fa-hand-o-right',
        'fa-hand-o-left',
        'fa-hand-o-up',
        'fa-hand-o-down',
        'fa-arrow-circle-left',
        'fa-arrow-circle-right',
        'fa-arrow-circle-up',
        'fa-arrow-circle-down',
        'fa-globe',
        'fa-wrench',
        'fa-tasks',
        'fa-filter',
        'fa-briefcase',
        'fa-arrows-alt',
        'fa-group',
        'fa-users',
        'fa-chain',
        'fa-link',
        'fa-cloud',
        'fa-flask',
        'fa-cut',
        'fa-scissors',
        'fa-copy',
        'fa-files-o',
        'fa-paperclip',
        'fa-save',
        'fa-floppy-o',
        'fa-square',
        'fa-navicon',
        'fa-reorder',
        'fa-bars',
        'fa-list-ul',
        'fa-list-ol',
        'fa-strikethrough',
        'fa-underline',
        'fa-table',
        'fa-magic',
        'fa-truck',
        'fa-pinterest',
        'fa-pinterest-square',
        'fa-google-plus-square',
        'fa-google-plus',
        'fa-money',
        'fa-caret-down',
        'fa-caret-up',
        'fa-caret-left',
        'fa-caret-right',
        'fa-columns',
        'fa-unsorted',
        'fa-sort',
        'fa-sort-down',
        'fa-sort-desc',
        'fa-sort-up',
        'fa-sort-asc',
        'fa-envelope',
        'fa-linkedin',
        'fa-rotate-left',
        'fa-undo',
        'fa-legal',
        'fa-gavel',
        'fa-dashboard',
        'fa-tachometer',
        'fa-comment-o',
        'fa-comments-o',
        'fa-flash',
        'fa-bolt',
        'fa-sitemap',
        'fa-umbrella',
        'fa-paste',
        'fa-clipboard',
        'fa-lightbulb-o',
        'fa-exchange',
        'fa-cloud-download',
        'fa-cloud-upload',
        'fa-user-md',
        'fa-stethoscope',
        'fa-suitcase',
        'fa-bell-o',
        'fa-coffee',
        'fa-cutlery',
        'fa-file-text-o',
        'fa-building-o',
        'fa-hospital-o',
        'fa-ambulance',
        'fa-medkit',
        'fa-fighter-jet',
        'fa-beer',
        'fa-h-square',
        'fa-plus-square',
        'fa-angle-double-left',
        'fa-angle-double-right',
        'fa-angle-double-up',
        'fa-angle-double-down',
        'fa-angle-left',
        'fa-angle-right',
        'fa-angle-up',
        'fa-angle-down',
        'fa-desktop',
        'fa-laptop',
        'fa-tablet',
        'fa-mobile-phone',
        'fa-mobile',
        'fa-circle-o',
        'fa-quote-left',
        'fa-quote-right',
        'fa-spinner',
        'fa-circle',
        'fa-mail-reply',
        'fa-reply',
        'fa-github-alt',
        'fa-folder-o',
        'fa-folder-open-o',
        'fa-smile-o',
        'fa-frown-o',
        'fa-meh-o',
        'fa-gamepad',
        'fa-keyboard-o',
        'fa-flag-o',
        'fa-flag-checkered',
        'fa-terminal',
        'fa-code',
        'fa-mail-reply-all',
        'fa-reply-all',
        'fa-star-half-empty',
        'fa-star-half-full',
        'fa-star-half-o',
        'fa-location-arrow',
        'fa-crop',
        'fa-code-fork',
        'fa-unlink',
        'fa-chain-broken',
        'fa-question',
        'fa-info',
        'fa-exclamation',
        'fa-superscript',
        'fa-subscript',
        'fa-eraser',
        'fa-puzzle-piece',
        'fa-microphone',
        'fa-microphone-slash',
        'fa-shield',
        'fa-calendar-o',
        'fa-fire-extinguisher',
        'fa-rocket',
        'fa-maxcdn',
        'fa-chevron-circle-left',
        'fa-chevron-circle-right',
        'fa-chevron-circle-up',
        'fa-chevron-circle-down',
        'fa-anchor',
        'fa-unlock-alt',
        'fa-bullseye',
        'fa-ellipsis-h',
        'fa-ellipsis-v',
        'fa-rss-square',
        'fa-play-circle',
        'fa-ticket',
        'fa-minus-square',
        'fa-minus-square-o',
        'fa-level-up',
        'fa-level-down',
        'fa-check-square',
        'fa-pencil-square',
        'fa-external-link-square',
        'fa-share-square',
        'fa-compass',
        'fa-toggle-down',
        'fa-caret-square-o-down',
        'fa-toggle-up',
        'fa-caret-square-o-up',
        'fa-toggle-right',
        'fa-caret-square-o-right',
        'fa-euro',
        'fa-eur',
        'fa-gbp',
        'fa-dollar',
        'fa-usd',
        'fa-rupee',
        'fa-inr',
        'fa-cny',
        'fa-rmb',
        'fa-yen',
        'fa-jpy',
        'fa-ruble',
        'fa-rouble',
        'fa-rub',
        'fa-won',
        'fa-krw',
        'fa-bitcoin',
        'fa-btc',
        'fa-file',
        'fa-file-text',
        'fa-sort-alpha-asc',
        'fa-sort-alpha-desc',
        'fa-sort-amount-asc',
        'fa-sort-amount-desc',
        'fa-sort-numeric-asc',
        'fa-sort-numeric-desc',
        'fa-thumbs-up',
        'fa-thumbs-down',
        'fa-youtube-square',
        'fa-youtube',
        'fa-xing',
        'fa-xing-square',
        'fa-youtube-play',
        'fa-dropbox',
        'fa-stack-overflow',
        'fa-instagram',
        'fa-flickr',
        'fa-adn',
        'fa-bitbucket',
        'fa-bitbucket-square',
        'fa-tumblr',
        'fa-tumblr-square',
        'fa-long-arrow-down',
        'fa-long-arrow-up',
        'fa-long-arrow-left',
        'fa-long-arrow-right',
        'fa-apple',
        'fa-windows',
        'fa-android',
        'fa-linux',
        'fa-dribbble',
        'fa-skype',
        'fa-foursquare',
        'fa-trello',
        'fa-female',
        'fa-male',
        'fa-gittip',
        'fa-gratipay',
        'fa-sun-o',
        'fa-moon-o',
        'fa-archive',
        'fa-bug',
        'fa-vk',
        'fa-weibo',
        'fa-renren',
        'fa-pagelines',
        'fa-stack-exchange',
        'fa-arrow-circle-o-right',
        'fa-arrow-circle-o-left',
        'fa-toggle-left',
        'fa-caret-square-o-left',
        'fa-dot-circle-o',
        'fa-wheelchair',
        'fa-vimeo-square',
        'fa-turkish-lira',
        'fa-try',
        'fa-plus-square-o',
        'fa-space-shuttle',
        'fa-slack',
        'fa-envelope-square',
        'fa-wordpress',
        'fa-openid',
        'fa-institution',
        'fa-bank',
        'fa-university',
        'fa-mortar-board',
        'fa-graduation-cap',
        'fa-yahoo',
        'fa-google',
        'fa-reddit',
        'fa-reddit-square',
        'fa-stumbleupon-circle',
        'fa-stumbleupon',
        'fa-delicious',
        'fa-digg',
        'fa-pied-piper-pp',
        'fa-pied-piper-alt',
        'fa-drupal',
        'fa-joomla',
        'fa-language',
        'fa-fax',
        'fa-building',
        'fa-child',
        'fa-paw',
        'fa-spoon',
        'fa-cube',
        'fa-cubes',
        'fa-behance',
        'fa-behance-square',
        'fa-steam',
        'fa-steam-square',
        'fa-recycle',
        'fa-automobile',
        'fa-car',
        'fa-cab',
        'fa-taxi',
        'fa-tree',
        'fa-spotify',
        'fa-deviantart',
        'fa-soundcloud',
        'fa-database',
        'fa-file-pdf-o',
        'fa-file-word-o',
        'fa-file-excel-o',
        'fa-file-powerpoint-o',
        'fa-file-photo-o',
        'fa-file-picture-o',
        'fa-file-image-o',
        'fa-file-zip-o',
        'fa-file-archive-o',
        'fa-file-sound-o',
        'fa-file-audio-o',
        'fa-file-movie-o',
        'fa-file-video-o',
        'fa-file-code-o',
        'fa-vine',
        'fa-codepen',
        'fa-jsfiddle',
        'fa-life-bouy',
        'fa-life-buoy',
        'fa-life-saver',
        'fa-support',
        'fa-life-ring',
        'fa-circle-o-notch',
        'fa-ra',
        'fa-resistance',
        'fa-rebel',
        'fa-ge',
        'fa-empire',
        'fa-git-square',
        'fa-git',
        'fa-y-combinator-square',
        'fa-yc-square',
        'fa-hacker-news',
        'fa-tencent-weibo',
        'fa-qq',
        'fa-wechat',
        'fa-weixin',
        'fa-send',
        'fa-paper-plane',
        'fa-send-o',
        'fa-paper-plane-o',
        'fa-history',
        'fa-circle-thin',
        'fa-header',
        'fa-paragraph',
        'fa-sliders',
        'fa-share-alt',
        'fa-share-alt-square',
        'fa-bomb',
        'fa-soccer-ball-o',
        'fa-futbol-o',
        'fa-tty',
        'fa-binoculars',
        'fa-plug',
        'fa-slideshare',
        'fa-twitch',
        'fa-yelp',
        'fa-newspaper-o',
        'fa-wifi',
        'fa-calculator',
        'fa-paypal',
        'fa-google-wallet',
        'fa-cc-visa',
        'fa-cc-mastercard',
        'fa-cc-discover',
        'fa-cc-amex',
        'fa-cc-paypal',
        'fa-cc-stripe',
        'fa-bell-slash',
        'fa-bell-slash-o',
        'fa-trash',
        'fa-copyright',
        'fa-at',
        'fa-eyedropper',
        'fa-paint-brush',
        'fa-birthday-cake',
        'fa-area-chart',
        'fa-pie-chart',
        'fa-line-chart',
        'fa-lastfm',
        'fa-lastfm-square',
        'fa-toggle-off',
        'fa-toggle-on',
        'fa-bicycle',
        'fa-bus',
        'fa-ioxhost',
        'fa-angellist',
        'fa-cc',
        'fa-shekel',
        'fa-sheqel',
        'fa-ils',
        'fa-meanpath',
        'fa-buysellads',
        'fa-connectdevelop',
        'fa-dashcube',
        'fa-forumbee',
        'fa-leanpub',
        'fa-sellsy',
        'fa-shirtsinbulk',
        'fa-simplybuilt',
        'fa-skyatlas',
        'fa-cart-plus',
        'fa-cart-arrow-down',
        'fa-diamond',
        'fa-ship',
        'fa-user-secret',
        'fa-motorcycle',
        'fa-street-view',
        'fa-heartbeat',
        'fa-venus',
        'fa-mars',
        'fa-mercury',
        'fa-intersex',
        'fa-transgender',
        'fa-transgender-alt',
        'fa-venus-double',
        'fa-mars-double',
        'fa-venus-mars',
        'fa-mars-stroke',
        'fa-mars-stroke-v',
        'fa-mars-stroke-h',
        'fa-neuter',
        'fa-genderless',
        'fa-facebook-official',
        'fa-pinterest-p',
        'fa-whatsapp',
        'fa-server',
        'fa-user-plus',
        'fa-user-times',
        'fa-hotel',
        'fa-bed',
        'fa-viacoin',
        'fa-train',
        'fa-subway',
        'fa-medium',
        'fa-yc',
        'fa-y-combinator',
        'fa-optin-monster',
        'fa-opencart',
        'fa-expeditedssl',
        'fa-battery',
        'fa-battery-full',
        'fa-battery-three-quarters',
        'fa-battery-half',
        'fa-battery-quarter',
        'fa-battery-empty',
        'fa-mouse-pointer',
        'fa-i-cursor',
        'fa-object-group',
        'fa-object-ungroup',
        'fa-sticky-note',
        'fa-sticky-note-o',
        'fa-cc-jcb',
        'fa-cc-diners-club',
        'fa-clone',
        'fa-balance-scale',
        'fa-hourglass-o',
        'fa-hourglass-start',
        'fa-hourglass-half',
        'fa-hourglass-end',
        'fa-hourglass',
        'fa-hand-grab-o',
        'fa-hand-rock-o',
        'fa-hand-stop-o',
        'fa-hand-paper-o',
        'fa-hand-scissors-o',
        'fa-hand-lizard-o',
        'fa-hand-spock-o',
        'fa-hand-pointer-o',
        'fa-hand-peace-o',
        'fa-trademark',
        'fa-registered',
        'fa-creative-commons',
        'fa-gg',
        'fa-gg-circle',
        'fa-tripadvisor',
        'fa-odnoklassniki',
        'fa-odnoklassniki-square',
        'fa-get-pocket',
        'fa-wikipedia-w',
        'fa-safari',
        'fa-chrome',
        'fa-firefox',
        'fa-opera',
        'fa-internet-explorer',
        'fa-tv',
        'fa-television',
        'fa-contao',
        'fa-amazon',
        'fa-calendar-plus-o',
        'fa-calendar-minus-o',
        'fa-calendar-times-o',
        'fa-calendar-check-o',
        'fa-industry',
        'fa-map-pin',
        'fa-map-signs',
        'fa-map-o',
        'fa-map',
        'fa-commenting',
        'fa-commenting-o',
        'fa-houzz',
        'fa-vimeo',
        'fa-black-tie',
        'fa-fonticons',
        'fa-reddit-alien',
        'fa-edge',
        'fa-credit-card-alt',
        'fa-codiepie',
        'fa-modx',
        'fa-fort-awesome',
        'fa-usb',
        'fa-product-hunt',
        'fa-mixcloud',
        'fa-scribd',
        'fa-pause-circle',
        'fa-pause-circle-o',
        'fa-stop-circle',
        'fa-stop-circle-o',
        'fa-shopping-bag',
        'fa-shopping-basket',
        'fa-hashtag',
        'fa-bluetooth',
        'fa-bluetooth-b',
        'fa-percent',
        'fa-gitlab',
        'fa-wpbeginner',
        'fa-wpforms',
        'fa-envira',
        'fa-universal-access',
        'fa-wheelchair-alt',
        'fa-question-circle-o',
        'fa-blind',
        'fa-audio-description',
        'fa-volume-control-phone',
        'fa-braille',
        'fa-assistive-listening-systems',
        'fa-asl-interpreting',
        'fa-american-sign-language-interpreting',
        'fa-deafness',
        'fa-hard-of-hearing',
        'fa-deaf',
        'fa-glide',
        'fa-glide-g',
        'fa-signing',
        'fa-sign-language',
        'fa-low-vision',
        'fa-viadeo',
        'fa-viadeo-square',
        'fa-snapchat',
        'fa-snapchat-ghost',
        'fa-snapchat-square',
        'fa-pied-piper',
        'fa-first-order',
        'fa-yoast',
        'fa-themeisle',
        'fa-google-plus-circle',
        'fa-google-plus-official',
        'fa-fa',
        'fa-font-awesome',
        'fa-handshake-o',
        'fa-envelope-open',
        'fa-envelope-open-o',
        'fa-linode',
        'fa-address-book',
        'fa-address-book-o',
        'fa-vcard',
        'fa-address-card',
        'fa-vcard-o',
        'fa-address-card-o',
        'fa-user-circle',
        'fa-user-circle-o',
        'fa-user-o',
        'fa-id-badge',
        'fa-drivers-license',
        'fa-id-card',
        'fa-drivers-license-o',
        'fa-id-card-o',
        'fa-quora',
        'fa-free-code-camp',
        'fa-telegram',
        'fa-thermometer',
        'fa-thermometer-full',
        'fa-thermometer-three-quarters',
        'fa-thermometer-half',
        'fa-thermometer-quarter',
        'fa-thermometer-empty',
        'fa-shower',
        'fa-bathtub',
        'fa-bath',
        'fa-podcast',
        'fa-window-maximize',
        'fa-window-minimize',
        'fa-window-restore',
        'fa-times-rectangle',
        'fa-window-close',
        'fa-times-rectangle-o',
        'fa-window-close-o',
        'fa-bandcamp',
        'fa-grav',
        'fa-etsy',
        'fa-imdb',
        'fa-ravelry',
        'fa-eercast',
        'fa-microchip',
        'fa-snowflake-o',
        'fa-superpowers',
        'fa-wpexplorer',
        'fa-meetup'
    );

    for ($index = 0; $index < count($arreglo_iconos); $index++) {
        $arreglo_icon[] = '<i class="fa ' . $arreglo_iconos[$index] . '"></i>';
    }
    $arreglo_t[0] = $arreglo_iconos;
    $arreglo_t[1] = $arreglo_icon;
    return $arreglo_t;
}
?>

<script>
    document.titlesMod = [{'title': 'Modulo dependencia', 'width': '200'},
        {'title': 'ID', 'width': '50'}];

    var arreglo_icons = [
        'fa-heart',
        'fa-star',
        'fa-star-o',
        'fa-user',
        'fa-film',
        'fa-th-large',
        'fa-th',
        'fa-th-list',
        'fa-check',
        'fa-remove',
        'fa-close',
        'fa-times',
        'fa-search-plus',
        'fa-search-minus',
        'fa-power-off',
        'fa-signal',
        'fa-gear',
        'fa-cog',
        'fa-trash-o',
        'fa-home',
        'fa-file-o',
        'fa-clock-o',
        'fa-road',
        'fa-download',
        'fa-arrow-circle-o-down',
        'fa-arrow-circle-o-up',
        'fa-inbox',
        'fa-play-circle-o',
        'fa-rotate-right',
        'fa-repeat',
        'fa-refresh',
        'fa-list-alt',
        'fa-lock',
        'fa-flag',
        'fa-headphones',
        'fa-volume-off',
        'fa-volume-down',
        'fa-volume-up',
        'fa-qrcode',
        'fa-barcode',
        'fa-tag',
        'fa-tags',
        'fa-book',
        'fa-bookmark',
        'fa-print',
        'fa-camera',
        'fa-font',
        'fa-bold',
        'fa-italic',
        'fa-text-height',
        'fa-text-width',
        'fa-align-left',
        'fa-align-center',
        'fa-align-right',
        'fa-align-justify',
        'fa-list',
        'fa-dedent',
        'fa-outdent',
        'fa-indent',
        'fa-video-camera',
        'fa-photo',
        'fa-image',
        'fa-picture-o',
        'fa-pencil',
        'fa-map-marker',
        'fa-adjust',
        'fa-tint',
        'fa-edit',
        'fa-pencil-square-o',
        'fa-share-square-o',
        'fa-check-square-o',
        'fa-arrows',
        'fa-step-backward',
        'fa-fast-backward',
        'fa-backward',
        'fa-play',
        'fa-pause',
        'fa-stop',
        'fa-forward',
        'fa-fast-forward',
        'fa-step-forward',
        'fa-eject',
        'fa-chevron-left',
        'fa-chevron-right',
        'fa-plus-circle',
        'fa-minus-circle',
        'fa-times-circle',
        'fa-check-circle',
        'fa-question-circle',
        'fa-info-circle',
        'fa-crosshairs',
        'fa-times-circle-o',
        'fa-check-circle-o',
        'fa-ban',
        'fa-arrow-left',
        'fa-arrow-right',
        'fa-arrow-up',
        'fa-arrow-down',
        'fa-mail-forward',
        'fa-share',
        'fa-expand',
        'fa-compress',
        'fa-plus',
        'fa-minus',
        'fa-asterisk',
        'fa-exclamation-circle',
        'fa-gift',
        'fa-leaf',
        'fa-fire',
        'fa-eye',
        'fa-eye-slash',
        'fa-warning',
        'fa-exclamation-triangle',
        'fa-plane',
        'fa-calendar',
        'fa-random',
        'fa-comment',
        'fa-magnet',
        'fa-chevron-up',
        'fa-chevron-down',
        'fa-retweet',
        'fa-shopping-cart',
        'fa-folder',
        'fa-folder-open',
        'fa-arrows-v',
        'fa-arrows-h',
        'fa-bar-chart-o',
        'fa-bar-chart',
        'fa-twitter-square',
        'fa-facebook-square',
        'fa-camera-retro',
        'fa-key',
        'fa-gears',
        'fa-cogs',
        'fa-comments',
        'fa-thumbs-o-up',
        'fa-thumbs-o-down',
        'fa-star-half',
        'fa-heart-o',
        'fa-sign-out',
        'fa-linkedin-square',
        'fa-thumb-tack',
        'fa-external-link',
        'fa-sign-in',
        'fa-trophy',
        'fa-github-square',
        'fa-upload',
        'fa-lemon-o',
        'fa-phone',
        'fa-square-o',
        'fa-bookmark-o',
        'fa-phone-square',
        'fa-twitter',
        'fa-facebook-f',
        'fa-facebook',
        'fa-github',
        'fa-unlock',
        'fa-credit-card',
        'fa-feed',
        'fa-rss',
        'fa-hdd-o',
        'fa-bullhorn',
        'fa-bell',
        'fa-certificate',
        'fa-hand-o-right',
        'fa-hand-o-left',
        'fa-hand-o-up',
        'fa-hand-o-down',
        'fa-arrow-circle-left',
        'fa-arrow-circle-right',
        'fa-arrow-circle-up',
        'fa-arrow-circle-down',
        'fa-globe',
        'fa-wrench',
        'fa-tasks',
        'fa-filter',
        'fa-briefcase',
        'fa-arrows-alt',
        'fa-group',
        'fa-users',
        'fa-chain',
        'fa-link',
        'fa-cloud',
        'fa-flask',
        'fa-cut',
        'fa-scissors',
        'fa-copy',
        'fa-files-o',
        'fa-paperclip',
        'fa-save',
        'fa-floppy-o',
        'fa-square',
        'fa-navicon',
        'fa-reorder',
        'fa-bars',
        'fa-list-ul',
        'fa-list-ol',
        'fa-strikethrough',
        'fa-underline',
        'fa-table',
        'fa-magic',
        'fa-truck',
        'fa-pinterest',
        'fa-pinterest-square',
        'fa-google-plus-square',
        'fa-google-plus',
        'fa-money',
        'fa-caret-down',
        'fa-caret-up',
        'fa-caret-left',
        'fa-caret-right',
        'fa-columns',
        'fa-unsorted',
        'fa-sort',
        'fa-sort-down',
        'fa-sort-desc',
        'fa-sort-up',
        'fa-sort-asc',
        'fa-envelope',
        'fa-linkedin',
        'fa-rotate-left',
        'fa-undo',
        'fa-legal',
        'fa-gavel',
        'fa-dashboard',
        'fa-tachometer',
        'fa-comment-o',
        'fa-comments-o',
        'fa-flash',
        'fa-bolt',
        'fa-sitemap',
        'fa-umbrella',
        'fa-paste',
        'fa-clipboard',
        'fa-lightbulb-o',
        'fa-exchange',
        'fa-cloud-download',
        'fa-cloud-upload',
        'fa-user-md',
        'fa-stethoscope',
        'fa-suitcase',
        'fa-bell-o',
        'fa-coffee',
        'fa-cutlery',
        'fa-file-text-o',
        'fa-building-o',
        'fa-hospital-o',
        'fa-ambulance',
        'fa-medkit',
        'fa-fighter-jet',
        'fa-beer',
        'fa-h-square',
        'fa-plus-square',
        'fa-angle-double-left',
        'fa-angle-double-right',
        'fa-angle-double-up',
        'fa-angle-double-down',
        'fa-angle-left',
        'fa-angle-right',
        'fa-angle-up',
        'fa-angle-down',
        'fa-desktop',
        'fa-laptop',
        'fa-tablet',
        'fa-mobile-phone',
        'fa-mobile',
        'fa-circle-o',
        'fa-quote-left',
        'fa-quote-right',
        'fa-spinner',
        'fa-circle',
        'fa-mail-reply',
        'fa-reply',
        'fa-github-alt',
        'fa-folder-o',
        'fa-folder-open-o',
        'fa-smile-o',
        'fa-frown-o',
        'fa-meh-o',
        'fa-gamepad',
        'fa-keyboard-o',
        'fa-flag-o',
        'fa-flag-checkered',
        'fa-terminal',
        'fa-code',
        'fa-mail-reply-all',
        'fa-reply-all',
        'fa-star-half-empty',
        'fa-star-half-full',
        'fa-star-half-o',
        'fa-location-arrow',
        'fa-crop',
        'fa-code-fork',
        'fa-unlink',
        'fa-chain-broken',
        'fa-question',
        'fa-info',
        'fa-exclamation',
        'fa-superscript',
        'fa-subscript',
        'fa-eraser',
        'fa-puzzle-piece',
        'fa-microphone',
        'fa-microphone-slash',
        'fa-shield',
        'fa-calendar-o',
        'fa-fire-extinguisher',
        'fa-rocket',
        'fa-maxcdn',
        'fa-chevron-circle-left',
        'fa-chevron-circle-right',
        'fa-chevron-circle-up',
        'fa-chevron-circle-down',
        'fa-anchor',
        'fa-unlock-alt',
        'fa-bullseye',
        'fa-ellipsis-h',
        'fa-ellipsis-v',
        'fa-rss-square',
        'fa-play-circle',
        'fa-ticket',
        'fa-minus-square',
        'fa-minus-square-o',
        'fa-level-up',
        'fa-level-down',
        'fa-check-square',
        'fa-pencil-square',
        'fa-external-link-square',
        'fa-share-square',
        'fa-compass',
        'fa-toggle-down',
        'fa-caret-square-o-down',
        'fa-toggle-up',
        'fa-caret-square-o-up',
        'fa-toggle-right',
        'fa-caret-square-o-right',
        'fa-euro',
        'fa-eur',
        'fa-gbp',
        'fa-dollar',
        'fa-usd',
        'fa-rupee',
        'fa-inr',
        'fa-cny',
        'fa-rmb',
        'fa-yen',
        'fa-jpy',
        'fa-ruble',
        'fa-rouble',
        'fa-rub',
        'fa-won',
        'fa-krw',
        'fa-bitcoin',
        'fa-btc',
        'fa-file',
        'fa-file-text',
        'fa-sort-alpha-asc',
        'fa-sort-alpha-desc',
        'fa-sort-amount-asc',
        'fa-sort-amount-desc',
        'fa-sort-numeric-asc',
        'fa-sort-numeric-desc',
        'fa-thumbs-up',
        'fa-thumbs-down',
        'fa-youtube-square',
        'fa-youtube',
        'fa-xing',
        'fa-xing-square',
        'fa-youtube-play',
        'fa-dropbox',
        'fa-stack-overflow',
        'fa-instagram',
        'fa-flickr',
        'fa-adn',
        'fa-bitbucket',
        'fa-bitbucket-square',
        'fa-tumblr',
        'fa-tumblr-square',
        'fa-long-arrow-down',
        'fa-long-arrow-up',
        'fa-long-arrow-left',
        'fa-long-arrow-right',
        'fa-apple',
        'fa-windows',
        'fa-android',
        'fa-linux',
        'fa-dribbble',
        'fa-skype',
        'fa-foursquare',
        'fa-trello',
        'fa-female',
        'fa-male',
        'fa-gittip',
        'fa-gratipay',
        'fa-sun-o',
        'fa-moon-o',
        'fa-archive',
        'fa-bug',
        'fa-vk',
        'fa-weibo',
        'fa-renren',
        'fa-pagelines',
        'fa-stack-exchange',
        'fa-arrow-circle-o-right',
        'fa-arrow-circle-o-left',
        'fa-toggle-left',
        'fa-caret-square-o-left',
        'fa-dot-circle-o',
        'fa-wheelchair',
        'fa-vimeo-square',
        'fa-turkish-lira',
        'fa-try',
        'fa-plus-square-o',
        'fa-space-shuttle',
        'fa-slack',
        'fa-envelope-square',
        'fa-wordpress',
        'fa-openid',
        'fa-institution',
        'fa-bank',
        'fa-university',
        'fa-mortar-board',
        'fa-graduation-cap',
        'fa-yahoo',
        'fa-google',
        'fa-reddit',
        'fa-reddit-square',
        'fa-stumbleupon-circle',
        'fa-stumbleupon',
        'fa-delicious',
        'fa-digg',
        'fa-pied-piper-pp',
        'fa-pied-piper-alt',
        'fa-drupal',
        'fa-joomla',
        'fa-language',
        'fa-fax',
        'fa-building',
        'fa-child',
        'fa-paw',
        'fa-spoon',
        'fa-cube',
        'fa-cubes',
        'fa-behance',
        'fa-behance-square',
        'fa-steam',
        'fa-steam-square',
        'fa-recycle',
        'fa-automobile',
        'fa-car',
        'fa-cab',
        'fa-taxi',
        'fa-tree',
        'fa-spotify',
        'fa-deviantart',
        'fa-soundcloud',
        'fa-database',
        'fa-file-pdf-o',
        'fa-file-word-o',
        'fa-file-excel-o',
        'fa-file-powerpoint-o',
        'fa-file-photo-o',
        'fa-file-picture-o',
        'fa-file-image-o',
        'fa-file-zip-o',
        'fa-file-archive-o',
        'fa-file-sound-o',
        'fa-file-audio-o',
        'fa-file-movie-o',
        'fa-file-video-o',
        'fa-file-code-o',
        'fa-vine',
        'fa-codepen',
        'fa-jsfiddle',
        'fa-life-bouy',
        'fa-life-buoy',
        'fa-life-saver',
        'fa-support',
        'fa-life-ring',
        'fa-circle-o-notch',
        'fa-ra',
        'fa-resistance',
        'fa-rebel',
        'fa-ge',
        'fa-empire',
        'fa-git-square',
        'fa-git',
        'fa-y-combinator-square',
        'fa-yc-square',
        'fa-hacker-news',
        'fa-tencent-weibo',
        'fa-qq',
        'fa-wechat',
        'fa-weixin',
        'fa-send',
        'fa-paper-plane',
        'fa-send-o',
        'fa-paper-plane-o',
        'fa-history',
        'fa-circle-thin',
        'fa-header',
        'fa-paragraph',
        'fa-sliders',
        'fa-share-alt',
        'fa-share-alt-square',
        'fa-bomb',
        'fa-soccer-ball-o',
        'fa-futbol-o',
        'fa-tty',
        'fa-binoculars',
        'fa-plug',
        'fa-slideshare',
        'fa-twitch',
        'fa-yelp',
        'fa-newspaper-o',
        'fa-wifi',
        'fa-calculator',
        'fa-paypal',
        'fa-google-wallet',
        'fa-cc-visa',
        'fa-cc-mastercard',
        'fa-cc-discover',
        'fa-cc-amex',
        'fa-cc-paypal',
        'fa-cc-stripe',
        'fa-bell-slash',
        'fa-bell-slash-o',
        'fa-trash',
        'fa-copyright',
        'fa-at',
        'fa-eyedropper',
        'fa-paint-brush',
        'fa-birthday-cake',
        'fa-area-chart',
        'fa-pie-chart',
        'fa-line-chart',
        'fa-lastfm',
        'fa-lastfm-square',
        'fa-toggle-off',
        'fa-toggle-on',
        'fa-bicycle',
        'fa-bus',
        'fa-ioxhost',
        'fa-angellist',
        'fa-cc',
        'fa-shekel',
        'fa-sheqel',
        'fa-ils',
        'fa-meanpath',
        'fa-buysellads',
        'fa-connectdevelop',
        'fa-dashcube',
        'fa-forumbee',
        'fa-leanpub',
        'fa-sellsy',
        'fa-shirtsinbulk',
        'fa-simplybuilt',
        'fa-skyatlas',
        'fa-cart-plus',
        'fa-cart-arrow-down',
        'fa-diamond',
        'fa-ship',
        'fa-user-secret',
        'fa-motorcycle',
        'fa-street-view',
        'fa-heartbeat',
        'fa-venus',
        'fa-mars',
        'fa-mercury',
        'fa-intersex',
        'fa-transgender',
        'fa-transgender-alt',
        'fa-venus-double',
        'fa-mars-double',
        'fa-venus-mars',
        'fa-mars-stroke',
        'fa-mars-stroke-v',
        'fa-mars-stroke-h',
        'fa-neuter',
        'fa-genderless',
        'fa-facebook-official',
        'fa-pinterest-p',
        'fa-whatsapp',
        'fa-server',
        'fa-user-plus',
        'fa-user-times',
        'fa-hotel',
        'fa-bed',
        'fa-viacoin',
        'fa-train',
        'fa-subway',
        'fa-medium',
        'fa-yc',
        'fa-y-combinator',
        'fa-optin-monster',
        'fa-opencart',
        'fa-expeditedssl',
        'fa-battery',
        'fa-battery-full',
        'fa-battery-three-quarters',
        'fa-battery-half',
        'fa-battery-quarter',
        'fa-battery-empty',
        'fa-mouse-pointer',
        'fa-i-cursor',
        'fa-object-group',
        'fa-object-ungroup',
        'fa-sticky-note',
        'fa-sticky-note-o',
        'fa-cc-jcb',
        'fa-cc-diners-club',
        'fa-clone',
        'fa-balance-scale',
        'fa-hourglass-o',
        'fa-hourglass-start',
        'fa-hourglass-half',
        'fa-hourglass-end',
        'fa-hourglass',
        'fa-hand-grab-o',
        'fa-hand-rock-o',
        'fa-hand-stop-o',
        'fa-hand-paper-o',
        'fa-hand-scissors-o',
        'fa-hand-lizard-o',
        'fa-hand-spock-o',
        'fa-hand-pointer-o',
        'fa-hand-peace-o',
        'fa-trademark',
        'fa-registered',
        'fa-creative-commons',
        'fa-gg',
        'fa-gg-circle',
        'fa-tripadvisor',
        'fa-odnoklassniki',
        'fa-odnoklassniki-square',
        'fa-get-pocket',
        'fa-wikipedia-w',
        'fa-safari',
        'fa-chrome',
        'fa-firefox',
        'fa-opera',
        'fa-internet-explorer',
        'fa-tv',
        'fa-television',
        'fa-contao',
        'fa-amazon',
        'fa-calendar-plus-o',
        'fa-calendar-minus-o',
        'fa-calendar-times-o',
        'fa-calendar-check-o',
        'fa-industry',
        'fa-map-pin',
        'fa-map-signs',
        'fa-map-o',
        'fa-map',
        'fa-commenting',
        'fa-commenting-o',
        'fa-houzz',
        'fa-vimeo',
        'fa-black-tie',
        'fa-fonticons',
        'fa-reddit-alien',
        'fa-edge',
        'fa-credit-card-alt',
        'fa-codiepie',
        'fa-modx',
        'fa-fort-awesome',
        'fa-usb',
        'fa-product-hunt',
        'fa-mixcloud',
        'fa-scribd',
        'fa-pause-circle',
        'fa-pause-circle-o',
        'fa-stop-circle',
        'fa-stop-circle-o',
        'fa-shopping-bag',
        'fa-shopping-basket',
        'fa-hashtag',
        'fa-bluetooth',
        'fa-bluetooth-b',
        'fa-percent',
        'fa-gitlab',
        'fa-wpbeginner',
        'fa-wpforms',
        'fa-envira',
        'fa-universal-access',
        'fa-wheelchair-alt',
        'fa-question-circle-o',
        'fa-blind',
        'fa-audio-description',
        'fa-volume-control-phone',
        'fa-braille',
        'fa-assistive-listening-systems',
        'fa-asl-interpreting',
        'fa-american-sign-language-interpreting',
        'fa-deafness',
        'fa-hard-of-hearing',
        'fa-deaf',
        'fa-glide',
        'fa-glide-g',
        'fa-signing',
        'fa-sign-language',
        'fa-low-vision',
        'fa-viadeo',
        'fa-viadeo-square',
        'fa-snapchat',
        'fa-snapchat-ghost',
        'fa-snapchat-square',
        'fa-pied-piper',
        'fa-first-order',
        'fa-yoast',
        'fa-themeisle',
        'fa-google-plus-circle',
        'fa-google-plus-official',
        'fa-fa',
        'fa-font-awesome',
        'fa-handshake-o',
        'fa-envelope-open',
        'fa-envelope-open-o',
        'fa-linode',
        'fa-address-book',
        'fa-address-book-o',
        'fa-vcard',
        'fa-address-card',
        'fa-vcard-o',
        'fa-address-card-o',
        'fa-user-circle',
        'fa-user-circle-o',
        'fa-user-o',
        'fa-id-badge',
        'fa-drivers-license',
        'fa-id-card',
        'fa-drivers-license-o',
        'fa-id-card-o',
        'fa-quora',
        'fa-free-code-camp',
        'fa-telegram',
        'fa-thermometer',
        'fa-thermometer-full',
        'fa-thermometer-three-quarters',
        'fa-thermometer-half',
        'fa-thermometer-quarter',
        'fa-thermometer-empty',
        'fa-shower',
        'fa-bathtub',
        'fa-bath',
        'fa-podcast',
        'fa-window-maximize',
        'fa-window-minimize',
        'fa-window-restore',
        'fa-times-rectangle',
        'fa-window-close',
        'fa-times-rectangle-o',
        'fa-window-close-o',
        'fa-bandcamp',
        'fa-grav',
        'fa-etsy',
        'fa-imdb',
        'fa-ravelry',
        'fa-eercast',
        'fa-microchip',
        'fa-snowflake-o',
        'fa-superpowers',
        'fa-wpexplorer',
        'fa-meetup'];
    var colores_h = ['color:#C0C0C0;',
        'color:#808080;',
        'color:#000000;',
        'color:#FF0000;',
        'color:#800000;',
        'color:#FFC300;',
        'color:#808000;',
        'color:#5CB85C;',
        'color:#008000;',
        'color:#00FFFF;',
        'color:#008080;',
        'color:#0000FF;',
        'color:#000080;',
        'color:#FF00FF;',
        'color:#800080;'];
    var cadena = "<div id='des_act'><table style='text-align:center;font-size:10px;'>";
    var con = 0;
    for (var i = 0; i < arreglo_icons.length; i++) {
        var c_i = getRandomInt(0, 9);

        if (con == 0) {
            cadena += "<tr>";
        }
        cadena += '<td class=\'text-icon\'><a onclick=\'javascript:colocartexto("fa ' + arreglo_icons[i] + '")\'><i style="font-size:17px;' + colores_h[c_i] + '" class="d_icon fa ' + arreglo_icons[i] + '"></i></a></br>fa ' + arreglo_icons[i] + '</td>';
        if (con == 6) {
            cadena += "</tr>";
            con = -1;
        }
        con++;
    }
    cadena += "</div>";

    jQuery('#i_princam').webuiPopover({
        title: '<div><div style="display: inline-block;width:70%;"><strong>Resultados de busqueda</strong></div>' + '<div style="display: inline-block;width:30%;text-align:right;"><button onclick="hideMeAutoLst1();" style="background-color: transparent;border: none;" type="submit" class="btn btn-default" data-toggle="tooltip" title="Nuevo"><i style="font-size:21px;" aria-hidden="true" class="fa fa-times text-danger"></i></button></div>' + '</div>',
        width: 600,
        height: 300,
        padding: false,
        animation: 'pop',
        content: cadena,
        html: true,
    });
    function mostrar_iconos() {

        jQuery('#i_princam').webuiPopover({
            title: '<div><div style="display: inline-block;width:70%;"><strong>Resultados de busqueda</strong></div>' + '<div style="display: inline-block;width:30%;text-align:right;"><button onclick="hideMeAutoLst1();" style="background-color: transparent;border: none;" type="submit" class="btn btn-default" data-toggle="tooltip" title="Nuevo"><i style="font-size:21px;" aria-hidden="true" class="fa fa-times text-danger"></i></button></div>' + '</div>',
            width: 600,
            height: 300,
            padding: false,
            animation: 'pop',
            content: cadena,
            html: true,
        });

        //$("#ven_actv").html(cadena);
    }
    function colocartexto(texto) {
        document.getElementById('icono').value = '' + texto;
        jQuery("#i_princam").webuiPopover('hide');
        jQuery("#i_princam").removeClass();
        jQuery("#i_princam").attr('class', '' + texto);
        jQuery("#iconom").parent().html('<div><div id="iconom"><a href="javascript:mostrar_iconos();"><i class="' + texto + '"></i></a></div></div>');
        //document.getElementById('iconom').value = ''+'<i class="'+texto+'"></i>';
    }
    function getRandomInt(min, max) {
        return Math.floor(Math.random() * (max - min)) + min;
    }
    function hideMeAutoLst1() {
        jQuery('#i_princam').webuiPopover('hide');
    }
</script>

<script src="js/auto_disp.js"></script>
<script>
    function getSelect(target, liga, obj, entvalue, numAdd, initialize) {
        cadena = '';
        if (varval = document.getElementById(obj).value) {
            cadena = 'varval=' + varval + '&entvalue=' + entvalue + '&numAdd=' + numAdd + '&initialize=' + initialize;
            selflink = liga + '.php';
            cargar_xml(target, selflink, cadena);
        }
    }
    function initializeObjText() {
        args = initializeObjText.arguments;
        for (i = 0; i < args.length; i += 2) {
            document.getElementById(args[i]).value = args[i + 1];
        }
    }
</script>
<script>
    function getKeyFalse(e) {
        document.reTKey = true;
        if (window.event) {
            keynum = e.keyCode;
        } else if (e.which) {
            keynum = e.which;
        }
        if (keynum == 13) {
            if (document.notBussyKeyEnter == false) {
                document.reTKey = false;
            }
        }
    }//return reTKey;}

</script>
<script>
    function initializeObjText() {
        args = initializeObjText.arguments;
        e = args[0];
        if (window.event) {
            keynum = e.keyCode;
        } else if (e.which) {
            keynum = e.which;
        }
        if (document.notBussyKeyEnter && keynum != 13) {
            for (i = 1; i < args.length; i += 2) {
                document.getElementById(args[i]).value = args[i + 1];
            }
        }
    }
    function fnValida() {
        args = fnValida.arguments;
        if (document.getElementById(args[0]).value.length == 0) {
            hideMeAutoLst();
            xSpan = document.getElementById("span_" + args[1]);
            setMsgSpan(xSpan, '<img src="img/img43.gif" border="0" >', '#FF0000');
        }
    }

//fin autodisp
</script>
<SCRIPT SRC="js/poptext.js"></SCRIPT>
